In [1]:
# %%
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from dask_ml.preprocessing import Categorizer
from glum import GeneralizedLinearRegressor, TweedieDistribution
from lightgbm import LGBMRegressor
from sklearn.compose import ColumnTransformer
from sklearn.metrics import auc
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, SplineTransformer, StandardScaler

from ps3.data import create_sample_split, load_transform

In [2]:
# %%
# load data
df = load_transform()
df.head()

,IDpol,ClaimNb,Exposure,Area,VehPower,VehAge,DrivAge,BonusMalus,VehBrand,VehGas,Density,Region,ClaimAmount,ClaimAmountCut
0,1,0,0.10,D,5,0,5,50,B12,Regular,1217,R82,0.0,0.0
1,3,0,0.77,D,5,0,5,50,B12,Regular,1217,R82,0.0,0.0
2,5,0,0.75,B,6,1,5,50,B12,Diesel,54,R22,0.0,0.0
3,10,0,0.09,B,7,0,4,50,B12,Diesel,76,R72,0.0,0.0
4,11,0,0.84,B,7,0,4,50,B12,Diesel,76,R72,0.0,0.0

In [4]:
create_sample_split(df, 'IDpol')

,IDpol,ClaimNb,Exposure,Area,VehPower,VehAge,DrivAge,BonusMalus,VehBrand,VehGas,Density,Region,ClaimAmount,ClaimAmountCut,sample
0,1,0,0.10000,D,5,0,5,50,B12,Regular,1217,R82,0.0,0.0,train
1,3,0,0.77000,D,5,0,5,50,B12,Regular,1217,R82,0.0,0.0,test
2,5,0,0.75000,B,6,1,5,50,B12,Diesel,54,R22,0.0,0.0,test
3,10,0,0.09000,B,7,0,4,50,B12,Diesel,76,R72,0.0,0.0,test
4,11,0,0.84000,B,7,0,4,50,B12,Diesel,76,R72,0.0,0.0,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
678008,6114326,0,0.00274,E,4,0,5,50,B12,Regular,3317,R93,0.0,0.0,train
678009,6114327,0,0.00274,E,4,0,4,95,B12,Regular,9850,R11,0.0,0.0,test
678010,6114328,0,0.00274,D,6,1,4,50,B12,Diesel,1323,R82,0.0,0.0,train
678011,6114329,0,0.00274,B,4,0,5,50,B12,Regular,95,R26,0.0,0.0,train
678012,6114330,0,0.00274,B,7,1,2,54,B12,Diesel,65,R72,0.0,0.0,test